# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190306_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_description',
            field=models.TextField(max_length=350),
        ),
    ]
